[package]
name = "diagnostics"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "diagnostics"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[features]
default = []
otlp-exporter = [
    "dep:opentelemetry-otlp",
    "dep:reqwest",
    "reqwest/blocking",
    "reqwest/rustls-tls",
]

[dependencies]
app-protocol = { workspace = true }
runtime-protocol = { workspace = true }
utils-absolute-path = { workspace = true }
utils-string = { workspace = true }
chrono = { workspace = true }
gethostname = { workspace = true }
http = { workspace = true }
opentelemetry = { workspace = true, features = ["logs", "metrics", "trace"] }
opentelemetry-appender-tracing = { workspace = true }
opentelemetry-otlp = { workspace = true, features = [
    "grpc-tonic",
    "http-proto",
    "http-json",
    "logs",
    "metrics",
    "trace",
    "reqwest-blocking-client",
    "reqwest-rustls",
    "tls",
    "tls-roots",
], optional = true }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry_sdk = { workspace = true, features = [
    "experimental_trace_batch_span_processor_with_async_runtime",
    "experimental_metrics_custom_reader",
    "logs",
    "metrics",
    "rt-tokio",
    "testing",
    "trace",
] }
os_info = { workspace = true }
reqwest = { workspace = true, optional = true, features = ["blocking", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "json"] }
which = { workspace = true }
sys-locale = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
