[package]
name = "git-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
file-system = { workspace = true }
runtime-protocol = { workspace = true }
tokio = { workspace = true, features = ["process", "time"] }
utils-absolute-path = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }

[lib]
doctest = false
