[package]
name = "utils-sandbox-summary"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
model-provider-info = { workspace = true }
runtime-protocol = { workspace = true }
utils-absolute-path = { workspace = true }

[dev-dependencies]
utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }

[lib]
doctest = false
