// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reasoning effort values surfaced by the provider model catalog.
 */
export type ReasoningEffort = string;
