// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls output length/detail on capable reasoning models.
 * Serialized with lowercase values to match the provider request payload.
 */
export type Verbosity = "low" | "medium" | "high";
