[package]
edition.workspace = true
license.workspace = true
name = "model-provider-info"
version.workspace = true

[lib]
doctest = false
name = "model_provider_info"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
runtime-protocol = { workspace = true }
http = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
maplit = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }
utils-absolute-path = { workspace = true }
