[package]
edition.workspace = true
license.workspace = true
name = "utils-output-truncation"
version.workspace = true

[lints]
workspace = true

[dependencies]
runtime-protocol = { workspace = true }
utils-string = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lib]
doctest = false
