// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AutoReviewWarningNotification = {
/**
 * Thread target for the auto-review warning.
 */
threadId: string,
/**
 * Concise auto-review warning message for the user.
 */
message: string, };
