// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelUpgradeInfo = { model: string,
/**
 * Optional Sprite-owned copy for local model migration UI.
 */
upgradeCopy: string | null, modelLink: string | null, migrationMarkdown: string | null, };
