// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginAvailability } from "./PluginAvailability";
import type { PluginInstallPolicy } from "./PluginInstallPolicy";
import type { PluginInterface } from "./PluginInterface";
import type { PluginSetupPolicy } from "./PluginSetupPolicy";
import type { PluginSource } from "./PluginSource";

export type PluginSummary = { id: string,
/**
 * Version of the locally materialized plugin package when available.
 */
localVersion: string | null, name: string, source: PluginSource, installed: boolean, enabled: boolean, installPolicy: PluginInstallPolicy, setupPolicy: PluginSetupPolicy,
/**
 * Availability state for installing and using the plugin.
 */
availability: PluginAvailability, interface: PluginInterface | null, keywords: Array<string>, };
