// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogLoadErrorInfo } from "./CatalogLoadErrorInfo";
import type { PluginCatalogEntry } from "./PluginCatalogEntry";

/**
 * Installed Sprite-owned plugin catalog data discovered from local files or
 * generated in-memory by Sprite.
 */
export type PluginInstalledResponse = { catalogs: Array<PluginCatalogEntry>, catalogLoadErrors: Array<CatalogLoadErrorInfo>, };
