// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { CatalogInterface } from "./CatalogInterface";
import type { PluginSummary } from "./PluginSummary";

export type PluginCatalogEntry = { name: string,
/**
 * Local catalog file path when the catalog is backed by a local file.
 * Generated or in-memory catalogs do not have a local path.
 */
path: AbsolutePathBuf | null, interface: CatalogInterface | null, plugins: Array<PluginSummary>, };
