// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";

/**
 * Lists installed Sprite-owned plugins discovered from local catalogs.
 *
 * This protocol intentionally models only local catalog/plugin state plus
 * explicitly configured Git sources. It has no implicit network refresh knob.
 */
export type PluginInstalledParams = {
/**
 * Optional working directories used to discover repo catalogs.
 */
cwds?: Array<AbsolutePathBuf> | null,
/**
 * Additional uninstalled plugin names that should be returned when present locally.
 * This is used by mention surfaces that intentionally expose install entrypoints.
 */
installSuggestionPluginNames?: Array<string> | null, };
