// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeErrorInfo } from "./RuntimeErrorInfo";

export type TurnError = { message: string, errorInfo: RuntimeErrorInfo | null, additionalDetails: string | null, };
